### PR TITLE
Lee

### PR DESCRIPTION
**Pull request by IxCheanLee**
12/10/2024, 8:05pm

Contribution: finalization of Level Select scene using assets provided by design team
Contributor: Odulio, Reyes, Fernandez

Contribution: addition of idle animation in starting scene
Contributor: Escalante

Contribution: home to level select navigation
Contributor: Reyes, DelaCruz

Contribution: addition of player animations for movement, attack, dash, block
Contributor: Mariano

Contribution: creation of Level 1 Map scene with collision areas
Contributor: Pel

Contributions in need of fixing: Addition of options tab (currently corrupted)
Contributors: Carungcong L., De Castro, Ricafrente

Reviewed by: Lee

### CODE REVIEW

**Comment by IxCheanLee** [comment]
updates as of 12/10/2024, 9:11pm
Addition of back to start screen from home 
Contributor: Pedillaga

**Comment by IxCheanLee** [comment]
Updates as of 13/10/2024, 9:11pm

Contribution: fixing of (Addition of options tab)
Contributors: Carungcong L.

**Comment by IxCheanLee** [comment]
Updates as of 10/17/2024, 8:40 AM

Contribution: y sorting fix for collision layers
Contributor: Pel

Contribution: partial implementation of combat
Contributor: Mariano

Reviewed by: Lee

**Comment by IxCheanLee** [comment]
updates as of 18/10/2024, 9:46pm

Contribution: 
Added combat system for player and mobs
Added enemy spawning for level 1
Added healthbars for player and mobs
added Range indicator for boss attacks
Contributor: Mariano

Contribution: fixed some gaps in level 1 map (aka gray areas in the boundary)
added level select to level 1 transition
Contributor: Lee

Reviewed by: Lee

**Review by jtinosa — APPROVED** [review]

**Pull request merged**
