### PR TITLE
Lee

### PR DESCRIPTION
**Pull request by IxCheanLee**
current changes to files as of 28/09/2024, 8:22 pm

contributors:
Necessario - addition of clouds and bg
Bahaynon - added scene transition and anims
Reyes - updated Level Select scene | added Placeholder for level maps
Pedillaga - added Home Screen Button Function
Escalante - Added player idle animation on Tap to Start

Reviewed by: Lee

### CODE REVIEW

**Comment by IxCheanLee** [comment]
Additional integration as of 28/09/2024, 10:10 pm

Contributor: Odulio, Fernandez

Contributions:
Initial tests for animation/transitions
Temporary placements of function calls
Data or status not recorded/saved yet, start button will restart progress (animation state)

Reviewed by: Lee

**Comment by IxCheanLee** [comment]
Updates as of 29/09/2024, 9:58pm

Contributor: Tolentino
Contribution: addition of option button pressed

**Comment by IxCheanLee** [comment]
Updates as of 01/10/2024, 8:42pm

Contributor: Ricafrente

Contribution: Removal of button in options, and rounding of the corners of the square

**Comment by IxCheanLee** [comment]
Updates as of 03/10/2024, 7:16 pm
Contributor: De Castro

Contribution: Added graphics to leave game button

**Review by jtinosa — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Review by jtinosa — APPROVED** [review]

**Pull request merged**
