### PR TITLE
Homescreen_Side_Panel

### PR DESCRIPTION
**Pull request by erickjanpedillaga0908**

### CODE REVIEW

**Comment by jtinosa** [comment]
@erickjanpedillaga0908 @IxCheanLee please resolve the conflicts

**Comment by erickjanpedillaga0908** [comment]
Conflicts have been resolved

**Review by jtinosa — APPROVED** [review]

**Comment by jtinosa** [comment]
Pa-pull ng changes sa main para maresolve yung conflict

**Comment by erickjanpedillaga0908** [comment]
Okay na po ba Sir?

**Pull request merged**
